# Site settings
title: PraxPod
description: "Audio discussions and summaries for PYQs from PYQFort."
baseurl: "/PraxPod" # The subpath of your site, e.g., /blog. IMPORTANT for GitHub Pages.
url: "https://your-username.github.io" # Replace with your GitHub username

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections
collections:
  episodes:
    output: true
    permalink: /episodes/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "episodes"
    values:
      layout: "episode"
