# _config.yml
title: PraxPod
description: Stream audio summaries and discussions for PYQs.
baseurl: "/PraxPod"
url: "" # replace with your GH username/org

markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  episodes:
    output: true
    permalink: /episodes/:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "episodes"
      type: "episodes"
    values:
      layout: "episode"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md
  - SECURITY.MD
  - LICENSE
  - CONTRIBUTING.md

# Reduce server verbosity
webrick:
  host: localhost
  port: 4000
  logger: WEBrick::Log.new($stderr, WEBrick::Log::WARN)
